### ISSUE TITLE
Dash not working ingame when driving or standing

### ISSUE THREAD

**Issue by DerKuchen03** [JAGFx/ets2-dashboard-skin#173]
**Dash not working when driving and standing**

WHen i open the app and ets2 the webpage doesn't work and nothing shows up

**Device**

-Type: tablet
- OS fireos (amazon tablet running android)(also tried using a windows pc)

**Application**

- Version: __**1.7.3**__
- SCS Telemetry version: __**3.2.5**__
- Skin name:standard skin

**Logs**

> [Read this](https://github.com/JAGFx/ets2-dashboard-skin/blob/master/CONTRIBUTING.md#logs) to know how found logs

_Log: 2024-03-01T20:03:37.485Z | INFO | [server.listen] Euro Truck Simulator 2 dashboard is running at http://localhost:3000/ | {}
2024-03-01T20:03:37.488Z | INFO | Ready as Production | {}
2024-03-01T20:07:37.288Z | INFO | User connection | {"socketId":"PsZtNWfs9kVsDLkoAAAB"}
2024-03-01T20:11:54.045Z | INFO | User connection | {"socketId":"iw2ccuyOGCEZbsA_AAAD"}
2024-03-01T20:11:56.365Z | INFO | User connection | {"socketId":"PoZMu_D3Lga5qC_8AAAF"}
2024-03-01T20:20:17.531Z | INFO | User connection | {"socketId":"nNlNIJmvKqRuCcpbAAAH"}
2024-03-01T20:23:41.578Z | INFO | [server.listen] Euro Truck Simulator 2 dashboard is running at http://localhost:3000/ | {}
2024-03-01T20:23:41.580Z | INFO | Ready as Production | {}
2024-03-01T20:23:42.338Z | INFO | User connection | {"socketId":"BNiJxqm4gd0Xf6ABAAAB"}
2024-03-01T20:24:20.355Z | ERROR | uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at eval (webpack://my-webpack-project/../../lib/server.js?:136:51)
    at new Promise (<anonymous>)
    at initServer (webpack://my-webpack-project/../../lib/server.js?:118:10)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:61:5)
    at Function.runMain (pkg/prelude/bootstrap.js:1984:13)
    at node:internal/main/run_main_module:17:47 | {"error":{"code":"EADDRINUSE","errno":-4091,"syscall":"listen","address":"::","port":3000},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1372:16)\n    at listenInCluster (node:net:1420:12)\n    at Server.listen (node:net:1508:7)\n    at eval (webpack://my-webpack-project/../../lib/server.js?:136:51)\n    at new Promise (<anonymous>)\n    at initServer (webpack://my-webpack-project/../../lib/server.js?:118:10)\n    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:61:5)\n    at Function.runMain (pkg/prelude/bootstrap.js:1984:13)\n    at node:internal/main/run_main_module:17:47","exception":true,"date":"Fri Mar 01 2024 21:24:20 GMT+0100 (GMT+01:00)","process":{"pid":25328,"uid":null,"gid":null,"cwd":"D:\\download\\ets2-dashboard-skin_v1.7.3_node16","execPath":"D:\\download\\ets2-dashboard-skin_v1.7.3_node16\\ets2-dashboard-skin_v1.7.3.exe","version":"v16.15.0","argv":["D:\\download\\ets2-dashboard-skin_v1.7.3_node16\\ets2-dashboard-skin_v1.7.3.exe","C:\\snapshot\\customDefault\\servers\\default\\dist\\index.js"],"memoryUsage":{"rss":54820864,"heapTotal":30666752,"heapUsed":24966400,"external":3794533,"arrayBuffers":2709063}},"os":{"loadavg":[0,0,0],"uptime":2422},"trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1372,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1420,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":1508,"method":"listen","native":false},{"column":51,"file":"webpack://my-webpack-project/../../lib/server.js?","function":"eval","line":136,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":10,"file":"webpack://my-webpack-project/../../lib/server.js?","function":"initServer","line":118,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.runNextTicks [as _tickCallback]","line":61,"method":"runNextTicks [as _tickCallback]","native":false},{"column":13,"file":"pkg/prelude/bootstrap.js","function":"Function.runMain","line":1984,"method":"runMain","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":17,"method":null,"native":false}]}
2024-03-01T20:24:33.378Z | INFO | [server.listen] Euro Truck Simulator 2 dashboard is running at http://localhost:3000/ | {}
2024-03-01T20:24:33.380Z | INFO | Ready as Production | {}
2024-03-01T20:24:33.978Z | INFO | User connection | {"socketId":"QbOkwL4as2onxsMdAAAB"}
2024-03-01T20:29:14.620Z | INFO | User connection | {"socketId":"OhWkdyO56K2bcf_4AAAD"}
2024-03-01T20:29:19.345Z | INFO | User connection | {"socketId":"XMrSoezjyX8vnVYSAAAF"}
2024-03-01T20:29:28.905Z | INFO | User connection | {"socketId":"D02kZW7Ibni-rtl0AAAH"}
2024-03-01T20:31:49.839Z | INFO | User connection | {"socketId":"-BU157HFOaMD5QHrAAAJ"}
2024-03-01T20:37:18.318Z | INFO | User connection | {"socketId":"VlXJW1iOEJ0rHKDOAAAL"}
2024-03-01T20:41:17.697Z | INFO | User connection | {"socketId":"kJ2H6V4nRCCSDAjGAAAN"}
2024-03-01T20:43:06.995Z | INFO | [server.listen] Euro Truck Simulator 2 dashboard is running at http://localhost:3000/ | {}
2024-03-01T20:43:06.997Z | INFO | Ready as Production | {}
2024-03-01T20:43:07.114Z | INFO | User connection | {"socketId":"wwh0WkJdegS0UW4dAAAB"}
2024-03-01T20:55:50.330Z | INFO | User connection | {"socketId":"bQUuguk0WNri0OznAAAD"}

**Configuration**

ets:
{
	"unit_weight" :                            "kg",
	"unit_length" :                            "m",
	"unit_degrees" :                           "C",
	"unit_consumption" :                       "lpkm",
	"unit_volume" :                            "l",
	"unit_pressure" :                          "psi",
	"unit_speed" :                             "kph",
	"unit_currency" :                          "EUR",
	"jagfx_elements_right_oilTemperature" :    "true",
	"jagfx_elements_right_brakesTemperature" : "true",
	"jagfx_elements_right_brakesAirPressure" : "true",
	"jagfx_elements_right_fuel" :              "true",
	"jagfx_elements_right_fuelConsumption" :   "true",
	"jagfx_elements_right_cruiseControl" :     "true",
	"jagfx_elements_right_waterTemperature" :  "true",
	"jagfx_elements_right_batteryVoltage" :    "false",
	"jagfx_elements_mid_top_retarder" :        "true",
	"jagfx_elements_mid_top_parkingBrake" :    "true",
	"jagfx_elements_mid_top_beamHigh" :        "true",
	"jagfx_elements_mid_top_beamLow" :         "true",
	"jagfx_elements_mid_top_beacon" :          "false",
	"jagfx_elements_mid_bottom_rpm" :          "true",
	"jagfx_elements_mid_bottom_fuel" :         "true",
	"jagfx_elements_mid_bottom_speedLimit" :   "true",
	"jagfx_elements_right_restStop" :          "false",
	"jagfx_elements_mid_bottom_blinker_turn" : "true",
	"events_truck.refuel" :                    true,
	"events_truck.damage" :                    true,
	"events_truck.park" :                      true,
	"events_truck.engine" :                    true,
	"events_truck.electric" :                  true,
	"events_truck.emergency" :                 true,
	"events_truck.warning" :                   true,
	"events_truck.cruise-control-decrease" :   true,
	"events_truck.cruise-control-increase" :   true,
	"events_truck.cruise-control" :            true,
	"events_trailers.damage" :                 true,
	"events_trailers.coupling" :               true,
	"events_navigation.speed-limit" :          true,
	"events_job.started" :                     true,
	"events_job.finished" :                    true,
	"events_job.delivered" :                   true,
	"events_job.cancelled" :                   true,
	"events_game.refuel-payed" :               true,
	"events_game.train" :                      true,
	"events_game.ferry" :                      true,
	"events_game.tollgate" :                   true,
	"events_game.fine" :                       true,
	"events_game.pause" :                      true,
	"maps_elements_eta" :                      true,
	"maps_elements_speedAndGear" :             true,
	"maps_elements_mapControls" :              true,
	"maps_elements_speedLimit" :               true,
	"maps_elements_rotateWithPlayer" :         true,
	"maps_map_type" :                          "vanilla",
	"maps_map_tilesRemotePath" :               "https://raw.githubusercontent.com/Unicor-p/SCS_Map_Tiles/master/",
	"maps_map_activeMap" :                     null,
	"maps_map_navigationRemaining" :           "remaining_date",
	"maps_map_tilesVersion" :                  "latest",
	"jagfx_elements_right_map" :               false,
	"maps_map_tilesRemoteUseCustom" :          false,
	"maps_map_tilesRemoteCustomPath" :         null,
	"maps_general_debug" :                     false,
	"scania_default_menu": null
}

ats:
{
	"unit_weight" :                            "kg",
	"unit_length" :                            "m",
	"unit_degrees" :                           "C",
	"unit_consumption" :                       "lpkm",
	"unit_volume" :                            "l",
	"unit_pressure" :                          "psi",
	"unit_speed" :                             "kph",
	"unit_currency" :                          "USD",
	"jagfx_elements_right_oilTemperature" :    "true",
	"jagfx_elements_right_brakesTemperature" : "true",
	"jagfx_elements_right_brakesAirPressure" : "true",
	"jagfx_elements_right_fuel" :              "true",
	"jagfx_elements_right_fuelConsumption" :   "true",
	"jagfx_elements_right_cruiseControl" :     "true",
	"jagfx_elements_right_waterTemperature" :  "true",
	"jagfx_elements_right_batteryVoltage" :    "false",
	"jagfx_elements_mid_top_retarder" :        "true",
	"jagfx_elements_mid_top_parkingBrake" :    "true",
	"jagfx_elements_mid_top_beamHigh" :        "true",
	"jagfx_elements_mid_top_beamLow" :         "true",
	"jagfx_elements_mid_top_beacon" :          "false",
	"jagfx_elements_mid_bottom_rpm" :          "true",
	"jagfx_elements_mid_bottom_fuel" :         "true",
	"jagfx_elements_mid_bottom_speedLimit" :   "true",
	"jagfx_elements_right_restStop" :          "false",
	"jagfx_elements_mid_bottom_blinker_turn" : "true",
	"events_truck.refuel" :                    true,
	"events_truck.damage" :                    true,
	"events_truck.park" :                      true,
	"events_truck.engine" :                    true,
	"events_truck.electric" :                  true,
	"events_truck.emergency" :                 true,
	"events_truck.warning" :                   true,
	"events_truck.cruise-control-decrease" :   true,
	"events_truck.cruise-control-increase" :   true,
	"events_truck.cruise-control" :            true,
	"events_trailers.damage" :                 true,
	"events_trailers.coupling" :               true,
	"events_navigation.speed-limit" :          true,
	"events_job.started" :                     true,
	"events_job.finished" :                    true,
	"events_job.delivered" :                   true,
	"events_job.cancelled" :                   true,
	"events_game.refuel-payed" :               true,
	"events_game.train" :                      true,
	"events_game.ferry" :                      true,
	"events_game.tollgate" :                   true,
	"events_game.fine" :                       true,
	"events_game.pause" :                      true,
	"maps_elements_eta" :                      true,
	"maps_elements_speedAndGear" :             true,
	"maps_elements_mapControls" :              true,
	"maps_elements_speedLimit" :               true,
	"maps_elements_rotateWithPlayer" :         true,
	"maps_map_type" :                          "vanilla",
	"maps_map_tilesRemotePath" :               "https://raw.githubusercontent.com/Unicor-p/SCS_Map_Tiles/master/",
	"maps_map_activeMap" :                     null,
	"maps_map_navigationRemaining" :           "remaining_date",
	"maps_map_tilesVersion" :                  "latest",
	"jagfx_elements_right_map" :               false,
	"maps_map_tilesRemoteUseCustom" :          false,
	"maps_map_tilesRemoteCustomPath" :         null,
	"maps_general_debug" :                     false,
	"scania_default_menu": null
}

**Comment by JAGFx** [comment]
Can you fill all required information please.

Else I can't investigate with for only information "it's doesn't work"

**Comment by DerKuchen03** [comment]
i updated

> Can you fill all required information please.
> 
> Else I can't investigate with for only information "it's doesn't work"

i updated the comment. i sent just the title by an accident

**Comment by JAGFx** [comment]
@DerKuchen03 Can you get the new version and check if it's work ?

Note: You may need to expose explicitly the port. The [KNOW_ISSUES](https://github.com/JAGFx/ets2-dashboard-skin/blob/master/doc/KNOW_ISSUES.md#fixed) doc

**Comment by DerKuchen03** [comment]
> @DerKuchen03 Can you get the new version and check if it's work ?
> 
> Note: You may need to expose explicitly the port. The [KNOW_ISSUES](https://github.com/JAGFx/ets2-dashboard-skin/blob/master/doc/KNOW_ISSUES.md#fixed) doc



> @DerKuchen03 Can you get the new version and check if it's work ?
> 
> Note: You may need to expose explicitly the port. The [KNOW_ISSUES](https://github.com/JAGFx/ets2-dashboard-skin/blob/master/doc/KNOW_ISSUES.md#fixed) doc

it's still not working, sadly
